### PR TITLE
Correct text role error on pelican 3.7.1 on Xubuntu 16.04 

### PR DESCRIPTION
**Pull request by gotchafr**
```
DEBUG: Read file pelican/writing-content.rst -> Page
/home/gotcha/m.css/site/content/pelican/writing-content.rst:72: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:122: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:143: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:143: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:143: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:218: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:226: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:264: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:357: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:357: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:357: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:357: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:363: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:363: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:363: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:363: (ERROR/3) Unknown interpreted text role "rst".
/home/gotcha/m.css/site/content/pelican/writing-content.rst:412: (ERROR/3) Unknown interpreted text role "rst".
Makefile:65: recipe for target 'html' failed
make: *** [html] Error 13
```

### CODE REVIEW

**Comment by mosra** [comment]
Hey!

Thanks *a lot* for the patches, already integrated the first two as df354b72efa64783ac8bbb3eda7e39e14563197b and ba031f351c568cbc5e9fd6d0f8de7c1d1a88b353. I'm also on Linux, though the locale name wasn't a problem for me somehow. So I updated `pelicanconf.py` to just have it as you have it. Also fixed the generation error hopefully on all other possible places.

Now integrating the `libgs` patch :)

**Comment by mosra** [comment]
Integrated the rest as 489b91d156e8299820d6be5f3b2d7108d939ca22 (together with `chmod +x`) and also opened a PR upstream: https://github.com/tuxu/latex2svg/pull/2.

I'll update the README and docs to note the required TeX packages.

Thanks a lot for the contribution!

**Comment by gotchafr** [comment]
Hi Vladimir, thank _you_ for your nice work on pelican!
Just one last thing... I suggest you add a list of python packages to install... I had to find out the last two the hard way ;-) 

```
pip install pelican markdown typogrify
pip install Pyphen
pip install Pillow

```

Cheers...

**Comment by mosra** [comment]
Oh yeah, I'll do that as well :)

Not sure about markdown and typogrify though, m.css itself doesn't require them.

**Comment by gotchafr** [comment]
Great!
I think you are right, m.css does not need them... but they are sort of standard stuff for pelican... the last two are the more specific ones... 

I'm going to eat something I haven't had lunch yet... and thx again.

Cheers

**Comment by mosra** [comment]
I updated the docs in c6d0b2abe52f37f842a8e0e65dd26eb1c048d3a9, hopefully that's enough on all fronts :)

Closing as resolved, then.

**Pull request closed without merging**
