### PR TITLE
Fallback to fully qualified name in data type detection

### PR DESCRIPTION
**Pull request by sizmailov**

### CODE REVIEW

**Comment by mosra** [comment]
Not sure about this change -- in all cases (function arguments, function return types, ...) the type annotations are added only if explicitly provided. That way the user has the ability to keep a variable unannotated (for example if the type is too complex or irrelevant).

(Travis doesn't report PR build status anymore [because ugh](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798/16) and it forces me to do some migration or whatever, so here's the PR build status for reference: https://travis-ci.org/github/mosra/m.css/builds/688125152 )

**Comment by sizmailov** [comment]
Can you give an example when this behavior is unwanted?

**Comment by sizmailov** [comment]
I've changed the function a bit. It wont report built-in types:

```python
# type is obvious from value
a = 1        
v = "1.2.3"
# explicit types for builtin types are redundant:
attr: NoneType = None
flag: bool = False
```

Undocumented attributes without value on right hand are not really helpful in docs. It basically that says "there is a attribute of name `xxx`" is not really useful, type information makes things a bit better. 

WRT explicit annotation of functions/return types. They are explicit because it's the _only_ way to get them in python.

**Comment by mosra** [comment]
Um, no, still don't like this. There's no way to opt out of this behavior and some kind of "opinionated AI" that makes the decision for the user based on whether the type is builtin or not only complicates the implementation further. Also, what if the implicit type info is different from what you actually want to have shown in the docs? Or what if the implicit type is extremely complex (a recursive tuple of functions or whatnot) and you deliberately *do not want* to show it? I could introduce some config option to enable this, but don't want to -- too many config options is what makes Doxygen so brittle.

I'd say this -- if you want the vars to be annotated, add those annotations in the code. You'll want to add a docstring for those anyway in most cases, so why not the type also. If you don't want to have the type annotation in the code (because you need compatibility with Python 3.1 or whatnot), the annotation can be added in the `conf.py` for the documentation, right after you `import` that module -- this is what I do for [pybind-generated vars in magnum-bindings](https://github.com/mosra/magnum-bindings/blob/3d519d6c1992955979e31feb05a184430980a0bd/doc/python/conf.py#L71-L85), for example. If you want that to be automatic, you can even recursively `inspect` all modules in the `conf.py` and add the annotations that way. The flexibility is all there.

This automatic behavior is really not something that should be done by this script because it steals the control from the user, sorry.

**Comment by sizmailov** [comment]
Indeed, annotation/`conf.py` is right solution. I have just a couple of attributes that needs this, so not a big deal to handle. Project long-term health is superior to this bit of newcomer inconvenience, totally agreed.

**Pull request closed without merging**
