### PR TITLE
Remove Superfluous AnsiDefault class from console blocks

### LINKED ISSUE #156: Remove redundant g-AnsiDefault from formatted console output
From https://github.com/mosra/m.css/pull/151#issuecomment-640871837. @mosra noted

> Btw., one thing I noticed in the "ground truth" output:
>
> `<span class="g g-AnsiDefault" style="background-color: #5f00d7">`
> (And then repeated several times for all the colors.) Isn't the g g-AnsiDefault redundant in this case? I didn't look close enough to see if this is really an explicitly specified default in the input (in which case I'd say 
> it's okay), but if not then I think it isn't needed. Or is this a nested override of something defined above and thus it needs to be there?

The `g g-AnsiDefault` classes can be considered redundant. They _do_ give the end user a customization option whereby they can change the default foreground colour, but they're inconsistently applied. Sections of output without any ANSI SGR codes won't have this annotation, only ones with codes that affect the background colour. It probably does make sense keep from emitting the classes, making the `g-AnsiDefault` and `g-AnsiBackgroundDefault` CSS rules useless. `g-AnsiBrightDefault` is still useful.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #156

### CODE REVIEW

**Comment by blairconrad** [comment]
And now [green](https://travis-ci.org/github/mosra/m.css/builds/696823506)! I think the coverage numbers are maybe a little unreliable…
This is probably something you already know.

**Comment by blairconrad** [comment]
@mosra, have I missed an action item or anything? Are you still interested in this PR?

**Comment by mosra** [comment]
Hi, yes I am, I'm just extremely busy lately and this wasn't one of the things that are on fire, so I didn't have a chance to act upon it yet. I'll see what can I do in the next weeks or so, sorry for the extreme delays.

**Comment by blairconrad** [comment]
No worries! Sorry to bother you. Just wanted to confirm that I wasn't holding you up. Carry on. No rush. No need to further salve my feelings. :wink:

**Comment by mosra** [comment]
OK, finally got to this. I don't really remember the particulars anymore but the output looks good and it's all your code anyway, so I trust you to know what you're doing :)

Merged as 3383879bc40d00e1368046ae18f802257b07ee2d...fbb2de6873e6b49cc2a92d2e67a87793ccede1e9, again apologies for the delay.

**Comment by blairconrad** [comment]
> I don't really remember the particulars anymore but the output looks good and it's all your code anyway, so I trust you to know what you're doing :)

😆 

No worries about the timing. Thanks for the merge. And the theme!

**Pull request closed without merging**
