### PR TITLE
Python packaging

### LINKED ISSUE #82: missing setup.py-files for packaging
The pelican theme and plugins don't have a `setup.py` associated with it to make packaging easier.

https://packaging.python.org/tutorials/packaging-projects/

### PR DESCRIPTION
**Pull request by ashwinvis**
Packages all plugins (*.py), css and html data has to be explicitly added if it would be published on PyPI.

Fixes #82.
Previous attempt #97.

### CODE REVIEW

**Comment by MinchinWeb** [comment]
You probably want to add the Classifiers `Framework :: Pelican`, `Framework :: Pelican :: Themes`, and `Framework :: Pelican :: Plugins` (as appropriate).

**Comment by sizmailov** [comment]
This PR does not have `entry_points.console_scripts` in `setup.cfg`. 
it would nice to have aliases for `documentation/python.py` like `mcss-python` (+ same for doxygen).

**Comment by ashwinvis** [comment]
@sizmailov That can be difficult. Entry points are added to packages, and with this PR every file under "plugins" is regarded as a package. This is important for the next pelican release which supports import-able plugins.

While documentation can be added to the package, setting it as an entry point is not possible, the documentation is an installable python package  - which it is not.

**Comment by sizmailov** [comment]
IMO `documentation` is essential part of mcss and should be included in package whatever it takes. 

Turning `documentation` into a proper python package probably should be addressed in another PR (and this one should be rebased on top of it).

(Also note that CI [did not pass](https://travis-ci.org/github/mosra/m.css/builds/678605581), rebase on master should help)

**Comment by mosra** [comment]
Closing for the reasons described in #253. Might revisit this in the future, but for now packaging and especially regular versioned releases is extra effort I don't have bandwidth for. Sorry.

**Pull request closed without merging**
