### PR TITLE
fix encoding

### PR DESCRIPTION
**Pull request by DarkContact**
Here's a similar problem as in https://github.com/mosra/m.css/pull/115

Corrects the following characters:
mcss1
mcss2

### CODE REVIEW

**Comment by mosra** [comment]
Uh oh. Should I wait a bit before merging in case you discover even more? :)

**Comment by DarkContact** [comment]
Maybe. I don't know find anything today :)

**Comment by DarkContact** [comment]
I found a typo. That's all :)

**Comment by mosra** [comment]
Merged as b4b3ada4c02de8866cde75894126fd46c3648c8b and a2a7f07fdf1a52663f86d3da40b6884a7e7a2d8c, thanks again! :)

**Pull request closed without merging**
