### PR TITLE
[WIP] Infomation about which header to include for using class

### PR DESCRIPTION
**Pull request by machida-mn**
Part of [Important TODO](https://github.com/mosra/m.css/projects/5#card-6039499).

# Background

Doxygen html output displays the header file which defines the class body.

test5_test5_myclass_tp_class_template_reference_-_2018-10-16_22 35 20

However m.css doesn't hold the information about the source file, and then cannot display what file you should include.

# What will be changed

Extracting the `file` and `bodyfile` key in the location tag, each compounds hold the information about the source file location.

Also, utilizing the `bodyfile` value, class documentation can display while header to include for using the class. If the source file is documented, m.css create a link to the file.

mcss_example_myclass_class_mcss_example_doc_-_2018-10-16_22 22 38

### CODE REVIEW

**Comment by machida-mn** [comment]
Thank you for replying :+1: 

How should source file information for the unit other than class (function, enums, typedefs, ...) be appeared? If you have already had a design ideas, Let me know in more details. I'll try to achieve it as much as possible.

But for now, I change the information style to `#include <****.h>` as you mentioned.

**Comment by machida-mn** [comment]
OK, now updated.

image

**Comment by machida-mn** [comment]
> Would it be okay if this sits around for a whole? Let's say until the weekend or early next week?

Ok, don't worry. I want to work on an another work to improve your repository. I'll find the jobs in important TODOs.

**Comment by machida-mn** [comment]
This feature needs a extra work. Now I mark this PR as 'WIP'.

- [ ] If `bodyfile` key is not defined in location tag, use `file` key alternatively.
- [ ] If `include` tag is found under the root tag, utilize it. (this tag may be generated when \\class command used)

**Comment by mosra** [comment]
For the functions / typedefs / ... I thought it could be tucked somewhere in the bottom right corner of the dark-blue heading. With both the class-level and the function-level information I wanted it to waste as little vertical space as possible, so ideally putting them next to the `<h1>` tag somehow and similarly for the function header.

Re other work -- thank you for your interest! :+1:  However most of the things in *Important TODO* are very boring workarounds for broken things in Doxygen (for example functions that are marked with `@related` are present twice, or file documentation lacking namespace scope) or things that would require submitting patches to Doxygen itself... and that's absolutely *no fun thing* to do. Among the fun things could be adding support for QHP output (if you ever used QtCreator or KDevelop, the QHP files can be used for docs that are "one click away"). I think Visual Studio has something similar, if you use that (CHM files?). Or search for the <kbd>help needed</kbd> label in issues :)

**Comment by machida-mn** [comment]
Ok, but it will take about one week to complete, because I have to work on another task soon.

**Comment by mosra** [comment]
Sure, no problem ;)

**Comment by mosra** [comment]
> Would it be okay if this sits around for a whole? Let's say until the weekend or early next week? :)

Uh, sorry, I shouldn't have promised things that I'm unable to fulfill. For a more general estimate, I hope I can get back on this some time later this month.

**Comment by machida-mn** [comment]
> I shouldn't have promised things that I'm unable to fulfill. For a more general estimate, I hope I can get back on this some time later this month.

Ok, and please let me apologize to you for being late. I'll try to complete this task by the next Wednesday.

**Comment by mosra** [comment]
Picked this up and finished in aa6de409edc8f35cfe9270e7946fa875a2b1b651, mentioning you as a co-author. Unfortunately this uncovered a Doxygen bug that I have to fix to make the feature fully usable, but it's a good start nevertheless.

**Comment by mosra** [comment]
For the record, a fix for the above mentioned Doxygen bug is in doxygen/doxygen#6722.

**Pull request closed without merging**
