### PR TITLE
Support friend declarations in the Doxygen theme

### PR DESCRIPTION
**Pull request by mosra**
Should work and all, but Doxygen 1.8.13 that I have to use on Travis due to 1.8.14 being unusable (https://github.com/doxygen/doxygen/issues/6393) is producing invalid XML so half the tests just blow up there.

I had enough for today, so just leaving this here.

### CODE REVIEW

**Comment by mosra** [comment]
Merged into master, the test is disabled on Travis.

@jbakosi ping: it's ready now :)

**Comment by jbakosi** [comment]
Very cool! Can you remind me how this is now different? Friends did not even show up before (and now they do) if they were defined inline, correct?

**Comment by mosra** [comment]
Yes, exactly, friend function definitions documented in-class are now present in the docs (see the diff of this PR for a test showing what's done and what not).

I wanted to implement similar support for friend classes, but Doxygen output is unfortunately totally useless for these. So if you have a friend class declaration, that will still get ignored.

**Comment by jbakosi** [comment]
Cool, thanks, I don't think I have those.

**Pull request merged**
