### PR TITLE
Assert on buggy doxygen versions

### PR DESCRIPTION
**Pull request by sizmailov**
Add assert for buggy doxygen versions

### CODE REVIEW

**Comment by mosra** [comment]
Hmm, not sure about this -- the bug zoo in Doxygen is too complex and changes way too much between versions for this to be a simple version check. It could be also that 1.8.13 works perfectly well for other projects, it was just that you hit a bug :)

It could be a warning, but (especially in case of new projects being switched over to m.css) that'd get most probably drowned in all other output.

**Comment by sizmailov** [comment]
What about e.g.: `--skip-doxygen-version-check` flag to disable check & assertion ?

**Comment by mosra** [comment]
That only adds more complexity (and more API to document & test), and still wouldn't solve this fully -- 1.8.18 crashes for me on one project but not another, the upcoming 1.8.19 can't parse enums anymore, 1.8.16 was ignoring documented functions when certain kind of comments were used, 1.8.14 produced invalid XML in some cases, ... I would need to manage a huge version whitelist here and that's not an option.

**Comment by sizmailov** [comment]
An alternative would be to augment `doxygen.py` fired assertions with extra info about buggy doxygen versions to instruct user to update/downgrade, but it's tedious task.

**Comment by mosra** [comment]
Those assertions could fire also not just due to doxygen bugs, but due to bugs in my code (or when some unexpected input that nobody tried before is encountered). I'm afraid there's not much we can do about this.

**Comment by sizmailov** [comment]
I guess this PR should be close then

**Pull request closed without merging**
